version: '3.2'

# Docker compose file for Swarm cluster - stack deployment

# NOTE: Replace the image user id with your own Docker Hub repo id
services:
  db:
    image: clarenceho/docker-contact-db:1.0.0
    secrets:
      - contact_db_passwd
    environment:
      - POSTGRES_USER=contact
      - POSTGRES_PASSWORD_FILE=/run/secrets/contact_db_passwd
    networks:
      - db

  api:
    image: clarenceho/docker-contact-api:1.0.0
    ports:
      - target: 3000
        published: 9001
    secrets:
      - contact_db_passwd
    environment:
      - DB_HOST=db
      - DB_USER=contact
      - DB_DATABASE=contact
      - NODE_ENV=prd
    networks:
     - db
     - frontend

  web:
    image: clarenceho/docker-contact-web:1.0.0
    ports:
      - target: 80
        published: 9000
    networks:
      - frontend

networks:
  db:
    driver: overlay
  frontend:
    driver: overlay

secrets:
  contact_db_passwd:
    external: true
